# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypr7p9JnwmJP-Sdle6gFgc03SST9NPJu
"""

# Código para encontrar la raíz de una ecuación usando interpolación de Lagrange

#            Autor:
# Armando Augusto Valladares Uc
# Versión 1.01 : 17/02/2025

import numpy as np  # Librería para cálculos numéricos
import matplotlib.pyplot as plt  # Para graficar resultados

# Función que queremos analizar
def f(x):
    return x**3 - 6*x**2 + 11*x - 6

# Interpolación de Lagrange
def lagrange_interpolation(x, x_puntos, y_puntos):
    resultado = 0
    for i in range(len(x_puntos)):
        termino = y_puntos[i]
        for j in range(len(x_puntos)):
            if i != j:
                termino *= (x - x_puntos[j]) / (x_puntos[i] - x_puntos[j])
        resultado += termino
    return resultado

# Método de bisección para encontrar la raíz
def bisect(func, a, b, tol=1e-6, max_iter=100):
    if func(a) * func(b) > 0:
        raise ValueError("El intervalo no contiene una raíz")

    for _ in range(max_iter):
        c = (a + b) / 2
        if abs(func(c)) < tol or (b - a) / 2 < tol:
            return c
        if func(a) * func(c) < 0:
            b = c
        else:
            a = c
    return (a + b) / 2

# Definir los puntos de interpolación
x_points = np.array([1.0, 2.0, 3.0])
y_points = f(x_points)

# Generar puntos para graficar
x_vals = np.linspace(1.0, 3.0, 100)
y_interp = [lagrange_interpolation(x, x_points, y_points) for x in x_vals]

# Encontrar la raíz con bisección
root = bisect(lambda x: lagrange_interpolation(x, x_points, y_points), 1.0, 3.0)

# Calcular errores
errores_absolutos = np.abs(y_interp - f(x_vals))
errores_relativos = errores_absolutos / np.where(np.abs(f(x_vals)) == 0, 1, np.abs(f(x_vals)))
errores_cuadraticos = errores_absolutos**2

# Imprimir resultados
print(f"{'Iteración':<10}|{'x':<12}|{'Error absoluto':<18}|{'Error relativo':<18}|{'Error cuadrático'}")
print("-" * 80)

for i, (x_val, error_abs, error_rel, error_cuad) in enumerate(zip(x_vals, errores_absolutos, errores_relativos, errores_cuadraticos)):
    print(f"{i+1:<10}|{x_val:<12.6f}|{error_abs:<18.6e}|{error_rel:<18.6e}|{error_cuad:.6e}")

# Graficar errores y función interpolada
fig, ax = plt.subplots(1, 2, figsize=(14, 5))

ax[0].plot(x_vals, errores_absolutos, label="Error Absoluto", color='purple')
ax[0].plot(x_vals, errores_relativos, label="Error Relativo", color='orange')
ax[0].plot(x_vals, errores_cuadraticos, label="Error Cuadrático", color='brown')
ax[0].set_xlabel("x")
ax[0].set_ylabel("Errores")
ax[0].legend()
ax[0].grid(True)

ax[1].plot(x_vals, f(x_vals), label="f(x) = x³ - 6x² + 11x - 6", linestyle='dashed', color='blue')
ax[1].plot(x_vals, y_interp, label="Interpolación de Lagrange", color='red')
ax[1].axhline(0, color='black', linewidth=0.5, linestyle='--')
ax[1].axvline(root, color='green', linestyle='dotted', label=f"Raíz aproximada: {root:.4f}")
ax[1].scatter(x_points, y_points, color='black', label="Puntos de interpolación")
ax[1].set_xlabel("x")
ax[1].set_ylabel("f(x)")
ax[1].set_title("Interpolación y búsqueda de raíces")
ax[1].legend()
ax[1].grid(True)

# Guardar y mostrar la gráfica
plt.savefig("interpolacion_raices.png")
plt.show()

# Imprimir la raíz encontrada
print(f"La raíz aproximada usando interpolación es: {root:.4f}")